# Generated by Django 4.1.6 on 2023-03-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midMorningDjangoRegistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=30)),
                ('sup_email', models.CharField(max_length=30)),
                ('sup_prod', models.CharField(max_length=30)),
            ],
        ),
    ]
